language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node
git:
  depth: 3
branches:
  only:
  - master
script:
  npm run deploy-gh
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: gh-pages
  on:
    branch: master
